# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10, unique=True)),
                ('add_date', models.DateField(verbose_name='add_date')),
            ],
        ),
    ]
